# -*- coding: utf-8 -*-
"""1e_LightMode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FH0Sfc_-m5tQ7FVc3g9Exxod1gNv4D37
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# ... (código para ler o dataset - substitua pelo path de seu arquivo viia upload) ...

countryData = pd.read_csv("/content/countryData.csv").drop("Unnamed: 0", axis = 1)
countryData

def separacaoRegiao(countryData, coluna):
    regions = ["Norte America", "Asia", "Africa", "Sul da Asia"]
    countryPerData = countryData[["country", coluna]].dropna()
    countryPerData = countryPerData.groupby("country").sum()
    countryPerData = [countryPerData[coluna].iloc[1] + countryPerData[coluna].iloc[9],
                    countryPerData[coluna].iloc[2] + countryPerData[coluna].iloc[5],
                    countryPerData[coluna].iloc[3] + countryPerData[coluna].iloc[6] + countryPerData[coluna].iloc[7],
                    countryPerData[coluna].iloc[0] + countryPerData[coluna].iloc[4] + countryPerData[coluna].iloc[8]]
    return regions, countryPerData

def criandoGraficoPizza(countryData, coluna, titulo):
    regions, countryPerData = separacaoRegiao(countryData, coluna)
    plt.pie(countryPerData, labels=regions, autopct='%1.1f%%',
            startangle=140, colors=sns.color_palette("pastel"))
    plt.title(titulo)
    plt.show()

country = []
for x in countryData.loc[:, "country"]:
  if not x in country: country.append(x)
country

## 1-Gráfico de PIB per capta - Fundo Branco

# Definir uma paleta de cores pastel e facilitar a aplicação do estilo e da paleta de cores pastel.
palette = sns.color_palette("pastel")

# Criar a fura e o eixoig
plt.figure(figsize=(10, 5))  # Ajustar tamanho conforme necessário
ax = sns.lineplot(x="year", y="GDP Per Capita (USD)", hue="country", data=countryData, palette=palette)

# Personalizar o gráfico
ax.set_title("Evolução do GPD per capita por País", fontsize=20)  # Aumentar tamanho do título
ax.set_xlabel("Ano", fontsize=14)
ax.set_ylabel("PIB per capita (USD)", fontsize=14)
ax.grid(True, axis="y", alpha=0.5)  # Ajustar a aparência da grade

# Remover bordas superior e direita (opcional)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Ajustar a legenda (opcional)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)  # Mover a legenda para fora
plt.show()


## 2- Grafico Evolução temporal do acesso a eletricidade por país

palette = sns.color_palette("pastel")
plt.figure(figsize=(10, 5))
sns.lineplot(x="year", y="Access to electricity", hue="country", data=countryData, palette=palette)
plt.title("Evolução do Acesso à Eletricidade por País", fontsize=20)
plt.xlabel("Ano", fontsize=14)
plt.ylabel("Acesso à Eletricidade (%)", fontsize=14)
plt.grid(True, axis="x", alpha=0.5)  # Ajustar a aparência da grade
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)  # Mover a legenda para fora
plt.show()

